---

- hosts: xyz
  become: true
  vars:
    cwd: dir

  tasks:
    - name: Running pre-validation script on servers.
      script: "{{ cwd }}/scr_pre.sh"
      ignore_errors: yes

    - name: copying outputs file....
      fetch:
        src: /tmp/details.txt
        dest: "{{ cwd }}/output/pre_valdnt_{{ ansible_hostname }}_{{ ansible_date_time.date }}_{{ ansible_date_time.time }}.txt"
        flat: yes

    - debug:
        msg: "Output has been copied to {{ cwd }}/output/"
