---

- hosts: abc
  become: true

  vars:
    password: pwd
    username: uname

  tasks:
    - name: check user status
      shell: id {{ username }}
      ignore_errors: yes
      register: status
    - debug: 
        msg: "The {{ username }} doesn't exist on {{ ansible_hostname }}"
      when: status.rc != 0

    - name: password reset
      user:
        name: "{{ username }}"
        update_password: always
        password: "{{ password }}"
      register: result
      when: status.rc == 0
    - debug: 
        msg: > 
             {% if result.changed -%}
               The password has been reset for {{ username }} on {{ ansible_hostname }}
             {% else %}
               Password didn't reset for {{ username }} on {{ ansible_hostname }}
             {% endif %}
    
    - name: force change password
      command: "chage -d 0 {{ username }}"
      ignore_errors: yes

